# Generated by Django 4.2.7 on 2025-08-13 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='watchlist',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
